"""empty message

Revision ID: 3c23ca855d73
Revises: e590a661a8dc
Create Date: 2023-02-19 14:27:24.465942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3c23ca855d73"
down_revision = "e590a661a8dc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("rooms", schema=None) as batch_op:
        batch_op.add_column(sa.Column("difficulty", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("rooms", schema=None) as batch_op:
        batch_op.drop_column("difficulty")

    # ### end Alembic commands ###
