"""empty message

Revision ID: 4db5c427b317
Revises: 3c23ca855d73
Create Date: 2023-02-19 15:18:47.861612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4db5c427b317"
down_revision = "3c23ca855d73"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("rooms", schema=None) as batch_op:
        batch_op.drop_column("join_id")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("rooms", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "join_id",
                sa.INTEGER(),
                sa.Identity(
                    always=False,
                    start=1,
                    increment=1,
                    minvalue=1,
                    maxvalue=2147483647,
                    cycle=False,
                    cache=1,
                ),
                autoincrement=True,
                nullable=False,
            )
        )

    # ### end Alembic commands ###
