"""empty message

Revision ID: 8d6d215b7a92
Revises: 100394b84268
Create Date: 2023-02-16 16:56:44.686618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8d6d215b7a92"
down_revision = "100394b84268"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rooms",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("player_1_id", sa.Integer(), nullable=False),
        sa.Column("player_2_id", sa.Integer(), nullable=True),
        sa.Column("crossword_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("player_1_score", sa.Integer(), nullable=True),
        sa.Column("player_2_score", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["crossword_id"], ["crosswords.id"], name="room_crossword_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["player_1_id"], ["users.id"], name="room_user_1_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["player_2_id"], ["users.id"], name="room_user_2_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("rooms")
    # ### end Alembic commands ###
