"""empty message

Revision ID: aac31d7e31ae
Revises: e478bb8c519e
Create Date: 2023-02-16 18:30:03.202744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "aac31d7e31ae"
down_revision = "e478bb8c519e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("rooms", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("found_letters", sa.ARRAY(sa.String()), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("rooms", schema=None) as batch_op:
        batch_op.drop_column("found_letters")

    # ### end Alembic commands ###
