"""empty message

Revision ID: c2c3e698e15b
Revises: 03c1161aefff
Create Date: 2023-02-14 02:24:02.825499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
from sqlalchemy.sql.functions import now

revision = 'c2c3e698e15b'
down_revision = '03c1161aefff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False, server_default=now()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('results', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
