"""empty message

Revision ID: e590a661a8dc
Revises: aac31d7e31ae
Create Date: 2023-02-18 13:34:11.818896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e590a661a8dc"
down_revision = "aac31d7e31ae"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("crosswords", schema=None) as batch_op:
        batch_op.add_column(sa.Column("title", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("crosswords", schema=None) as batch_op:
        batch_op.drop_column("title")

    # ### end Alembic commands ###
